version: '3.8'

services:
  app:
    build: .
    ports:
      - "8087:8087"
    environment:
      - DB_SERVER=${DB_SERVER}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8087 --reload
